---
version: "3.7"
services:
  jenkins-flaky:
    build: .
    container_name: jenkins-pipeline-library-flaky
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs
      JAVA_OPTS: >-
        -Djenkins.install.runSetupWizard=false
        -Dhudson.model.UsageStatistics.disabled=true
    volumes:
      - type: volume
        source: jenkins_home_pipeline_library_flaky
        target: /var/jenkins_home
      - type: bind
        source: ./configs/jenkins.yaml
        target: /var/jenkins_home/casc_configs/jenkins.yaml
        read_only: true
      - type: bind
        source: ../.
        target: /var/pipeline-library
        read_only: true
      - type: bind
        source: ./configs/key
        target: /run/secrets/key
        read_only: true
      - type: bind
        source: ./configs/user
        target: /run/secrets/user
        read_only: true
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      pipeline-library-flaky:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION:-7.10.0}
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "path.data=/usr/share/elasticsearch/data/${STACK_VERSION:-7.10.0}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    ports:
      - "127.0.0.1:${ELASTICSEARCH_PORT:-9200}:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      retries: 10
      interval: 20s
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      pipeline-library-flaky:

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION:-7.10.0}
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "127.0.0.1:${KIBANA_PORT:-5601}:5601"
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    healthcheck:
      test: ["CMD", "curl", "--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://kibana:5601/"]
      retries: 10
      interval: 10s
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      pipeline-library-flaky:

volumes:
  jenkins_home_pipeline_library_flaky:
  esdata:
    driver: local

networks:
  pipeline-library-flaky:
    driver: bridge
