# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.network "private_network", ip: "192.168.33.1"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
    vb.cpus = 2
  end

  $script = <<-SCRIPT
  apt-get update
  apt install -y openjdk-8-jre-headless
  su - vagrant -c 'curl -s https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.9/swarm-client-3.9.jar > swarm-client.jar'
  su - vagrant -c 'nohup java -jar swarm-client.jar -labels "linux" -master http://10.0.2.2:8080 >/tmp/jenkins-swarm.log 2>&1 &'
  SCRIPT

  config.vm.provision "shell", inline: $script
end
